name: Test and Build

on:
  push:
    branches:
      - master
    paths:
      - '**/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Docker Setup
        uses: docker/setup-buildx-action@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flakes8

      # Test the code
      - name: Run Linting tests
        run: |
          flake8 --ignore=E501,F401 .

      - name: Docker Credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker tag
        id: version
        run: |
            VERSION=v$(date +%s)
            echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build . -t sampatel8543/demo-app:${{ env.VERSION }}

      # Push the Docker image
      - name: Push Docker image
        run: |
          docker push sampatel8543/demo-app:${{ env.VERSION }}